spring:
  application:
    name: user-provider
  mail:
    host: smtp.163.com
    username: 15976594566@163.com
    password: abc123456
    protocol: smtp
    port: 25
    default-encoding: UTF-8
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/abc
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.247.10
    port: 6379
  rabbitmq:
    host: 192.168.247.10
    port: 5672
    username: admin
    password: 123456
    publisher-confirms: true #交换机确认机制，是否确认回调
    publisher-returns: true #交换机确认机制，是否返回回调
    listener:
      simple:
        acknowledge-mode: manual #手动应答模式
        concurrency: 1 #指定最小消费者数量
        max-concurrency: 1 #指定最大消费者数量
        retry:
          enabled: true #是否支持重试
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8001
#配置别名
mybatis:
  type-aliases-package: com.doumi.pojo
  mapper-locations: classpath:/mappings/*.xml
