server:
  port: 8888
spring:
  application:
    name: user-consumer
#  redis:
#    host: 192.168.247.10
#    port: 6379
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8100/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    elasticsearch:
      enabled: false
    redis:
      enabled: false
  endpoint:
    health:
      show-details: always