spring:
  application:
    name: homePage-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/admin?setUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://admin:admin@localhost:8100/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    elasticsearch:
      enabled: false
    redis:
      enabled: false
  endpoint:
    health:
      show-details: ALWAYS
server:
  port: 8005
