server:
  port: 8004
spring:
  application:
    name: message-provider
#  security:
#    user:
#      name: admin
#      password: admin
  redis:
    port: 6379
    host: 192.168.247.10
  rabbitmq:
    host: 192.168.247.10
    port: 5672
    username: admin
    password: 123456
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always